### ISSUE TITLE
Add text boxes

### ISSUE THREAD

**Issue by tranek** [JohnMcLear/draw#118]
Something for down the road, basic text boxes.

**Comment by theelectricwiz** [comment]
This was going to be the next project of mine, if I get time. Was thinking of using an editable div to input/edit the text, then transfer it to a canvas element once the user is "done" (maybe clicking outside or a done button). Was going to have the ability to create text on a click (from either the draw or paint tools). Thoughts?

**Comment by theoryshaw** [comment]
Hi Jack,

How about something like this?...
![2015-12-03_10-17-25](https://cloud.githubusercontent.com/assets/507113/11566300/64dacad2-99a7-11e5-8889-3c00151738c7.gif)

This is a [Bluebeam](http://bluebeam.com/) interface, which a lot of architects/engineers use.

Obviously the arrows, leaders might be too much for an initial stab--perhaps more a road map thing.

Grab handles on the box might be too much too... perhaps just a text box that has a set width at this point.

In this UI example, which is hard to see in the .gif, the user double clicks on the text box to enter into edit mode.  To finish (or finish edit mode) the user clicks somewhere outside the text.

To move the text box around, the user just clicks and holds while dragging.

**Comment by theoryshaw** [comment]
Started a bounty source to help...

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=4243506)](https://www.bountysource.com/issues/4243506-add-text-boxes?utm_source=4243506&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by theoryshaw** [comment]
shot out some love too.... :)
... https://twitter.com/theoryshaw/status/672459464201515010

**Comment by theelectricwiz** [comment]
Cool. Cheers for the UI example. Have just started a branch (https://github.com/JohnMcLear/draw/tree/add-text) with a start in. Am currently going down the path of a contenteditable div for creating/editing the text and then inserting/updating it in the canvas once the edit is finished (as I haven't found an easy way to edit it directly in the canvas [unless you go down the route of something like this https://www.everythingfrontend.com/pages/canvas-text-editor-tutorial.html]). The bluebeam interface looks like a resonably good target.

**Comment by theoryshaw** [comment]
Hi Matteo(@teocomi ), thought i'd ping you into this convo, if interested.  In that, i think using draw.js instead of Window Paint for https://github.com/teocomi/BCFier would be pretty useful.  Especially with the BCF format moving away from files to a more web service format. Cheers.

**Comment by theelectricwiz** [comment]
Have implemented a basic (read *BASIC*) ability to add text to a canvas b344fca. Note you can't move or delete the text yet, but it's a start. To add, with the draw or paint tool selected, click on the canvas. That will draw an editable div. Write text to your hearts content, then click outside the div and hopefully presto.

**Comment by theoryshaw** [comment]
nice... per our previous convo, if you'd like me to test, feel free to push to http://sketch.openingdesign.com/ instance.

... or since you have AWS access, you can create alternate URL for testing, if you think that's a better approach.  Let me know if I need to create any sub domains, yadda yadda.

**Comment by theelectricwiz** [comment]
Just tried the textbox functionality I have out on my smartphone and was found that I was making little dots instead of starting textboxes, so I added a test to ignore any paths that were smaller than 5 (168fca1). This will mean that you won't be able to add dots. Do people need to be able to make dots?

**Comment by theoryshaw** [comment]
Yes, sometimes, unfortunately.  However, perhaps we can get 'dots' visually by clicking and dragging slighting, not just one quick click down. 

Actually, I think the current UI does that now.  That is, you have to drag slightly in order to make a 'dot'.

Do you have an instance up right now, where i could help you test 'what feels right'?

Cheers.

**Comment by theelectricwiz** [comment]
Have just updated http://sketch.openingdesign.com:9004/ to include this change.

**Comment by theoryshaw** [comment]
Cool... I see now.

How about (which is a more common user pattern i've seen) the user has to click a text button, then click in the canvas to place and start the text.

Afterwhich, the user can just double click somewhere over the text box to enter edit mode, no matter which tool is selected at the time.

**Comment by theoryshaw** [comment]
...then, of course, click off the text box somewhere, to exit edit mode.

**Comment by theelectricwiz** [comment]
Ok. Will adjust to work that way.

**Comment by theoryshaw** [comment]
Cool... JSYK, double clicking on an object to enter the edit mode of that object is a user pattern you see alot in other CAD/BIM software.

For example, I know this is not possible right now with Draw.js, but in the future, you could envision double clicking on a curve/line, and be able to move/edit the individual vertices of that curve/line....then click 'outside' to exit edit mode.

**Comment by theoryshaw** [comment]
This is awesome!  Feel free to put in your bountysource claim. 

BTW your work with zooming and text boxes pushed Draw.js to another escutcheon!

**Comment by theelectricwiz** [comment]
Try now. Have moved http://sketch.openingdesign.com:9004/ to the bleeding (edge) branch, which includes the double middle click and the unlimited panning. Thanks Ryan.

**Comment by theoryshaw** [comment]
feels good in chrome!

A few wonkies in firefox #212

**Comment by theelectricwiz** [comment]
Closing. Have added #214 for the extended capability.
