### ISSUE TITLE
Uploaded image not persisting...

### ISSUE THREAD

**Issue by theoryshaw** [JohnMcLear/draw#179]
video demonstrates the issue:
https://dl.dropboxusercontent.com/u/7117445/temp/image%20gone.mpg

Happens on all new instances, but this is the one i used for this video:
http://sketch.openingdesign.com/d/1toeOwALfP

Image uploaded: https://dl.dropboxusercontent.com/u/7117445/temp/test.jpg

**Comment by theoryshaw** [comment]
https://www.bountysource.com/issues/4212799-uploaded-image-not-persisting

**Comment by theoryshaw** [comment]
Hey John, any insight into this bug lately?

**Comment by JohnMcLear** [comment]
Afaik it's fixed, have you tested latest version?

**Comment by theoryshaw** [comment]
yeah, [pulled](https://github.com/OpeningDesign/draw/commit/122eb73ebbf11fa11b1d353a14b0561544213726) your latest branch changes over and restarted http://sketch.openingdesign.com

**Comment by JohnMcLear** [comment]
http://sketch.openingdesign.com/d/HPIUlyFDWl seems to be working okay?

**Comment by JohnMcLear** [comment]
I can't replicate on latest version.  Can you?

On 20 May 2015 14:28, Ryan Schultz <notifications@github.com> wrote:

Hey John, any insight into this bug lately?

**Comment by theoryshaw** [comment]
Hey, it's weird, it seems to be working now the 2nd time i tested after pulling your changes. :\
