### ISSUE TITLE
There was an error processing your settings.json file: Unexpected token }

### ISSUE THREAD

**Issue by ocdtrekkie** [JohnMcLear/draw#189]
I am getting this error when attempting to run this using the instructions on the readme. I looked at the settings.json file and it appears valid to me, so I'm not sure if I did something wrong or there's a bug. If you know what might cause this, I'd appreciate the advice.

**Comment by JohnMcLear** [comment]
Does your settings.json validate?  Try it.

On 22 May 2015 17:00, Jacob Weisz <notifications@github.com> wrote:

I am getting this error when attempting to run this using the instructions on the readme. I looked at the settings.json file and it appears valid to me, so I'm not sure if I did something wrong or there's a bug. If you know what might cause this, I'd appreciate the advice.

**Comment by ocdtrekkie** [comment]
My settings.json file seems to be the exact contents of settings.json.template in the repo. (Such and such validators specify that the file "is not JSON".

**Comment by JohnMcLear** [comment]
Sounds like it isn't...

On 22 May 2015 17:36, Jacob Weisz <notifications@github.com> wrote:

My settings.json file seems to be the exact contents of settings.json.template in the repo. (Such and such validators specify that the file "is not JSON".

**Comment by ocdtrekkie** [comment]
That appears to be the case.

So, your settings.json.template is not valid JSON either then, if I understand correctly. And if I understand the code correctly, the installDeps.sh file in your /bin seems to just copy the template to the settings file, if it doesn't exist.

**Comment by ocdtrekkie** [comment]
So, from my understanding, JSON cannot have comments: http://stackoverflow.com/questions/244777/can-i-comment-a-json-file

settings.json.template, however, states that comments are allowed, and it has comments. And the installDeps.sh file does not appear to strip them when creating settings.json.

**Comment by ocdtrekkie** [comment]
Ah, I see EtherDraw removes comments here: https://github.com/JohnMcLear/draw/commit/e3f9a6752b66e299de9f4f230b5030a5a2eb7761

Which is why settings.json, as created by EtherDraw, does not work correctly in a validator, but may/should work correctly in EtherDraw itself.

**Comment by ocdtrekkie** [comment]
Okay, I just found the bug.

Your "tool" line, the last uncommented config line in settings.json.template, has a trailing comma, and it shouldn't.

**Comment by ocdtrekkie** [comment]
Pull request #191 proposed to ensure this program works "out of the box" with readme instructions.

**Comment by JohnMcLear** [comment]
Shit..  Good spot.  No idea how I missed that....

**Comment by JohnMcLear** [comment]
Thanks for fix

**Comment by JohnMcLear** [comment]
PS sorry for short responses last night I was afk

**Comment by ocdtrekkie** [comment]
No problem, I got it working. Learned a thing or two figuring it out too.
