### ISSUE TITLE
Does not work with NodeJS 4.x.x

### ISSUE THREAD

**Issue by bytesnz** [JohnMcLear/draw#200]
Package canvas 1.2.1 does not work with NodeJS 4.x.x. Changing the package to 1.3.4 fixes the problem, but have not tested backwards capability.

**Comment by theelectricwiz** [comment]
Does anyone have a NodeJS installation < 4? If so, would you be able to see if the new-canvas-version branch 665367d installs/runs for you?

**Comment by JohnMcLear** [comment]
use nvm to manage multiple node versions on your box
