### ISSUE TITLE
Double middle click to zoom to extent of canvas

### ISSUE THREAD

**Issue by theelectricwiz** [JohnMcLear/draw#207]
From @theoryshaw Another user pattern you see quick a bit with various architect/eng tools, is double clicking with the middle mouse button(or wheel) and it zooms to the extents of the contents.

Will need to calculate coverage of canvas before can do this

**Comment by theelectricwiz** [comment]
@theoryshaw: Does it zoom to contain just the contents, or does it zoom to include 0,0 and the contents?

**Comment by theoryshaw** [comment]
Hey Jack, usually it zooms out to the extents of the contents. 

not 0,0

**Comment by theelectricwiz** [comment]
Ok. Thanks Ryan. Will make it work like that.

**Comment by theelectricwiz** [comment]
Completed in 86be08c. Will mark as completed once wrote tested a merged with develop.
