### ISSUE TITLE
Zoom/Pan in other 3 quadrants

### ISSUE THREAD

**Issue by theoryshaw** [JohnMcLear/draw#208]
This is a minor, nice to have...

![2015-12-06 08 14 22](https://cloud.githubusercontent.com/assets/507113/11613744/8fe194f8-9bf1-11e5-9f0f-a1e682acdf6d.jpg)

![2015-12-06 08 29 00](https://cloud.githubusercontent.com/assets/507113/11613795/a0d8bd84-9bf3-11e5-9a76-ba99b9167f85.jpg)

**Comment by theelectricwiz** [comment]
Ah. Would you like be able to zoom in the negatives? I suppose with all the other tools you can. Ok. Sounds good.

**Comment by theelectricwiz** [comment]
Completed in 510ed32
