### ISSUE TITLE
removing a project after first user left

### ISSUE THREAD

**Issue by srirammadduri** [JohnMcLear/draw#226]
Hi

i need to remove the project from list of projects after first user left.

Any Help

**Comment by theelectricwiz** [comment]
I have created an option that allows the deletion of a room after a specified time after the last person leaves the room (no one is left in the room) if that will do https://github.com/theelectricwiz/draw/blob/master/server.js#L60. It can either be specified as a command line argument, eg `$ npm start -- --removeUnused=5` or in the settings file `settings.json`

**Comment by srirammadduri** [comment]
Thanks for quick reply @theelectricwiz.So i need to add this line in settings.json as "removeUnused": 5 instead of "removeUnused": undefined.

is that right

**Comment by theelectricwiz** [comment]
Yes, that will remove the room after 5 minutes of no one being in the room. Note, this will occur even if you accidentally loose your connection with the server (and don't reconnect within the 5 minutes).

**Comment by srirammadduri** [comment]
most of the time i got this error on loading time
Uncaught TypeError: Cannot set property 'selected' of null

Any idea

**Comment by theelectricwiz** [comment]
@srirammadduri : Did you get anymore information with the error like a stack trace?

**Comment by srirammadduri** [comment]
Hi
the room remove from database not from array of projetcs

`{"projects":{"17928678wb1401":{"project":[["Layer",{"applyMatrix":true}]],"external_paths":{}},"17928632wb1401":{"project":[["Layer",{"applyMatrix":true}]],"external_paths":{}}}}`

**Comment by theelectricwiz** [comment]
Ah. Will try and get that fixed tomorrow morning (GMT). https://github.com/theelectricwiz/draw/issues/2

**Comment by srirammadduri** [comment]
Thanks @theelectricwiz still this is an issue not yet fixed

**Comment by theelectricwiz** [comment]
@srirammadduri: Yes. If I fix problem with the room not being removed from the list, will this resolve this issue for you?

**Comment by srirammadduri** [comment]
if you remove the room from projects object it resolves my problem.

and also Thanks for your support

**Comment by theelectricwiz** [comment]
Ok. Will fix.. and no problem.

**Comment by theelectricwiz** [comment]
@srirammadduri: have fixed the issue https://github.com/theelectricwiz/draw/commit/5ea7dfe0bde8e2e790f91cd73ff7468193576d5e.

**Comment by srirammadduri** [comment]
Ok Thanks i will test it and let you know.

**Comment by srirammadduri** [comment]
Thanks man it's working

**Comment by theelectricwiz** [comment]
Sweet.

**Comment by JohnMcLear** [comment]
tnx @theelectricwiz
