### ISSUE TITLE
Fetches "null" file?

### ISSUE THREAD

**Issue by rugk** [JohnMcLear/draw#243]
When creating a new Etherdraw canvas this file is fetched:

```
/d/null
```

No parameters are passed and an empty string (aka nothing) is returned.
So what's that? Is this request really necessary?

**Comment by JohnMcLear** [comment]
I don't see this: http://draw.etherpad.org/d/mIKGz1SA1B here

**Comment by JohnMcLear** [comment]
ah wait yes I do..

**Comment by JohnMcLear** [comment]
It only seems to be if you visit root URL IE http://draw.etherpad.org
