### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by politoxela** [JohnMcLear/draw#244]
Recently clone the project when running bin / run.sh and enter http: // localhost: 9002 / console returns me the error Can not read property '1' of null
which makes reference to me
`// Initialise Socket.io`
`base_path var = /(\/.+\/)d\/.*/.exec(window.location.pathname)[1];`
in draw.js
I only window appears with all the options but I can not do anything.

**Comment by JohnMcLear** [comment]
I have a feeling this is user error, please try to reinstall

**Comment by politoxela** [comment]
I went back to install it and gave me the same error, I solved taking draw.js they have in the demo.

**Comment by JohnMcLear** [comment]
Please close if solved

On 10 Jun 2016 22:33, politoxela <notifications@github.com> wrote:

I went back to install it and gave me the same error, I solved taking draw.js they have in the demo.
