### ISSUE TITLE
What about using Greenkeeper? 

### ISSUE THREAD

**Issue by rugk** [JohnMcLear/draw#246]
It can help you to keep your npm dependencies updated.

See https://greenkeeper.io/ for more details.

@greenkeeperio

**Comment by ocdtrekkie** [comment]
Is this solving a problem this software is currently burdened by? This seems like... an advertisement more than an "issue". Maybe because you're spamming it on a bunch of the repositories I watch.

**Comment by rugk** [comment]
Yeah, why not suggest tit all of them. It is a question. I'm not affiliated  with Greenkeeper...

There is also https://docs.npmjs.com/cli/outdated and https://www.npmjs.com/package/npm-check-updates as (manual) alternatives.

What problem is it solving?
Well... just the problem of outdated dependencies and automatic updates of those.

**Comment by rugk** [comment]
You can also enable https://github.com/JohnMcLear/draw/network/dependencies for that feature now.
