### ISSUE TITLE
Collor palet appears all too often when internet load speed when drawing is lagging.

### ISSUE THREAD

**Issue by chopinregis** [JohnMcLear/draw#250]
when you hold down the pencil to draw, the color pallet comes up too fast if internet loading speed is lagging.
so if the internet load speed is lagging for what ever reason, having that pallet show up becomes annoying
because by the time you click, press and hold the click to draw, the lagging memory understands it as a command for the color palet
so perhaps a longger delay for hold down for the color palet
you had showed me a website where we can report bugs related to sketch I think
I can start writting these things I notice on there

**Comment by axoivs** [comment]
This might help with your problem: 9326e2f￼
