### ISSUE TITLE
Generating Different Whiteboards

### ISSUE THREAD

**Issue by axoivs** [JohnMcLear/draw#251]
How do you keep the Whiteboard from generating different whiteboards. I just want one whiteboard that is used instead of generating a new one every time you access the application.

**Comment by ocdtrekkie** [comment]
@axoivs When I ported EtherDraw to Sandstorm.io, I needed this functionality, and this is the commit I did it with: https://github.com/ocdtrekkie/draw/commit/c5f616dac94e23db905ee6d1ce609a944a152b8c

Scroll down to the changes to src/static/html/index.html where I simply replaced the random pad name generating function with a stationary board name.

**Comment by axoivs** [comment]
Ah yes, thank you.
