### ISSUE TITLE
Cannot find module 'canvas'

### ISSUE THREAD

**Issue by zaigham-mt** [JohnMcLear/draw#253]
Error: Cannot find module 'canvas'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

I even tried using npm install canvas still facing issue. Using OSX

**Comment by bytesnz** [comment]
Did canvas install correctly? You should be able to something like the below from the draw directory if it did
```
$ node
> var canvas = require('canvas');
undefined
> canvas
{ [Function: Canvas]
  version: '1.6.5',
  cairoVersion: '1.14.6',
  jpegVersion: '6b',
  gifVersion: '5.1.4',
  freetypeVersion: '2.7.1',
  Context2d: { [Function: CanvasRenderingContext2D] parseFont: [Function] },
  PNGStream: [Function: PNGStream],
  PDFStream: [Function: PDFStream],
  JPEGStream: [Function: JPEGStream],
  Image: { [Function: Image] MODE_IMAGE: 1, MODE_MIME: 2 },
  ImageData: [Function: ImageData],
  Font: [Function: Font] }
> 
```

**Comment by zaigham-mt** [comment]
var canvas = require('canvas');
Error: Cannot find module 'canvas'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at repl:1:14
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
> 


Plus I am unable to install canvas as facing following issues.

npm install canvas
\
> canvas@1.3.15 install /Users/zaighammaqsood/Downloads/draw-master/node_modules/canvas
> node-gyp rebuild

./util/has_lib.sh: line 30: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onex

**Comment by bytesnz** [comment]
See https://www.npmjs.com/package/canvas
You need to install the canvas dependencies first:
`brew install pkg-config cairo libpng jpeg giflib`

**Comment by zaigham-mt** [comment]
Is it supported for Windows too ?

**Comment by zaigham-mt** [comment]
Is there any option for rubber or to remove lines in this code.

**Comment by bytesnz** [comment]
With the cursor tool you can select a line and then delete it with the delete button.

**Comment by zaigham-mt** [comment]
It's working, thanks :)

**Comment by bytesnz** [comment]
np
