### ISSUE TITLE
Ubuntu 16.04, Module Version Mismatch

### ISSUE THREAD

**Issue by CodeMouse92** [JohnMcLear/draw#255]
I'm on Ubuntu 16.04 LTS (x64, server). I followed your instructions for setting this up, and all went well (except for `libjpeg62-turbo-dev` not existing...that's actually `libjpeg-turbo8-dev` on Ubuntu 16.04, it seems.)

When I run `bin/run.sh`, I get the following...

> Ensure that all dependencies are up to date...
> start...
> /opt/etherpad/draw/node_modules/bindings/bindings.js:83
>         throw e
>         ^
> 
> Error: Module version mismatch. Expected 48, got 46.
>     at Error (native)
>     at Object.Module._extensions..node (module.js:597:18)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at bindings (/opt/etherpad/draw/node_modules/bindings/bindings.js:76:44)
>     at Object.<anonymous> (/opt/etherpad/draw/node_modules/contextify/lib/contextify.js:1:96)
>     at Module._compile (module.js:570:32)

How do I fix this?

**Comment by carlesm95** [comment]
Try doing: apt-get install libcairo2-dev libjpeg-dev libgif-dev
