### ISSUE TITLE
bin/run.sh issue

### ISSUE THREAD

**Issue by johnfelipe** [JohnMcLear/draw#264]
felipe@cloud:~/draw$ bin/run.sh
	Ensure that all dependencies are up to date...

	> contextify@0.1.15 install /home/felipe/draw/node_modules/contextify
	> node-gyp rebuild

	make: Entering directory '/home/felipe/draw/node_modules/contextify/build'
	  CXX(target) Release/obj.target/contextify/src/contextify.o
	../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:
	../src/contextify.cc:131:68: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
			 Local<Object> wrapper = Nan::New(constructor)->NewInstance();
																		^
	In file included from /home/felipe/.node-gyp/8.3.0/include/node/v8.h:26:0,
					 from /home/felipe/.node-gyp/8.3.0/include/node/node.h:63,
					 from ../src/contextify.cc:1:
	/home/felipe/.node-gyp/8.3.0/include/node/v8.h:3792:52: note: declared here
	   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
														^
	/home/felipe/.node-gyp/8.3.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
	   declarator __attribute__((deprecated(message)))
	   ^
	../src/contextify.cc:150:16: error: ‘class v8::ObjectTemplate’ has no member named ‘SetAccessCheckCallbacks’
			 otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
					^
	../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)’:
	../src/contextify.cc:182:80: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
		   Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
																				  ^
	In file included from /home/felipe/.node-gyp/8.3.0/include/node/v8.h:26:0,
					 from /home/felipe/.node-gyp/8.3.0/include/node/node.h:63,
					 from ../src/contextify.cc:1:
	/home/felipe/.node-gyp/8.3.0/include/node/v8.h:3345:30: note: declared here
					 Local<Value> GetRealNamedProperty(Local<String> key));
								  ^
	/home/felipe/.node-gyp/8.3.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
	   declarator __attribute__((deprecated(message)))
	   ^
	../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)’:
	../src/contextify.cc:209:67: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
			 if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() |
																	   ^
	In file included from /home/felipe/.node-gyp/8.3.0/include/node/v8.h:26:0,
					 from /home/felipe/.node-gyp/8.3.0/include/node/node.h:63,
					 from ../src/contextify.cc:1:
	/home/felipe/.node-gyp/8.3.0/include/node/v8.h:3345:30: note: declared here
					 Local<Value> GetRealNamedProperty(Local<String> key));
								  ^
	/home/felipe/.node-gyp/8.3.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
	   declarator __attribute__((deprecated(message)))
	   ^
	../src/contextify.cc:210:71: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
			   !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()
																		 ^
	In file included from /home/felipe/.node-gyp/8.3.0/include/node/v8.h:26:0,
					 from /home/felipe/.node-gyp/8.3.0/include/node/node.h:63,
					 from ../src/contextify.cc:1:
	/home/felipe/.node-gyp/8.3.0/include/node/v8.h:3345:30: note: declared here
					 Local<Value> GetRealNamedProperty(Local<String> key));
								  ^
	/home/felipe/.node-gyp/8.3.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
	   declarator __attribute__((deprecated(message)))
	   ^
	contextify.target.mk:95: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
	make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
	make: Leaving directory '/home/felipe/draw/node_modules/contextify/build'
	gyp ERR! build error
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
	gyp ERR! stack     at emitTwo (events.js:125:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Linux 4.4.0-89-generic
	gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /home/felipe/draw/node_modules/contextify
	gyp ERR! node -v v8.3.0
	gyp ERR! node-gyp -v v3.6.2
	gyp ERR! not ok
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the contextify@0.1.15 install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/felipe/.npm/_logs/2017-08-14T14_44_48_540Z-debug.log
	start...
	DirtyDB is used. This is fine for testing but not recommended for production.
	module.js:491
		throw err;
		^

	Error: Cannot find module 'paper'
		at Function.Module._resolveFilename (module.js:489:15)
		at Function.Module._load (module.js:439:25)
		at Module.require (module.js:517:17)
		at require (internal/module.js:11:18)
		at Object.<anonymous> (/home/felipe/draw/src/util/draw.js:1:75)
		at Module._compile (module.js:573:30)
		at Object.Module._extensions..js (module.js:584:10)
		at Module.load (module.js:507:32)
		at tryModuleLoad (module.js:470:12)
		at Function.Module._load (module.js:462:3)

**Comment by bytesnz** [comment]
The build of contextify (an npm dependency) is failing on your system.

**Comment by johnfelipe** [comment]
i have ubuntu 16 and 

	felipe@cloud:~/draw$ node -v
	v8.3.0
	felipe@cloud:~/draw$ npm -v
	5.3.0

How solve it?

**Comment by johnfelipe** [comment]
Is not working with v8, working with v6

**Comment by JohnMcLear** [comment]
try now
