### ISSUE TITLE
Safari Mobile iOS 6 = partial view, no scrolling possible

### ISSUE THREAD

**Issue by juliendorra** [JohnMcLear/draw#82]
If you start a drawing on a desktop browser and then try to access it on an iPhone 5 with Safari Mobile, you can only view/draw on the top-left corner of the space.

There is no way to use double-touch to scroll or pinch-in / pinch-out. You are stuck seeing only a portion of the drawing space.

**Comment by theelectricwiz** [comment]
This has mostly been solved now with the panning/scaling I added. Only thing would be to add an indication that more of the drawing is not being seen. Will look into.
