### ISSUE TITLE
Drawing brush behavior counter-intuitive, opposite of most pseudo-natural brushes.

### ISSUE THREAD

**Issue by juliendorra** [JohnMcLear/draw#86]
The current behavior for the brush is:

the fastest you draw, the bigger the brush size.

From my experience with a lot of non-pressure sensitive, pseudo-natural brushes tools, for example on iPad, it's the opposite of how most brushes (all?) works when they implement that dynamic size behavior.

You generally have a brush that is thin when drawing quickly, allowing for fast sketches, and that pseudo-leak paint when going slow, allowing for filling.
It kind-of mimics the behavior of a real brushes.

(I actually found myself trying to sketch fast several times, each time rediscovering that I'm supposed to go slow…)

You might want to consider reversing the behavior.

**Comment by JohnMcLear** [comment]
Not going to change this behaviour now
